config/routes.rb
DynamicReport::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        get :update_task_status
      end
    end
  end

  resources :reports do
    member do
      get :generate_pdf
    end
  end
  match 'task_list/(:id)' => 'tasks#index' ,:as=>'task_list'
  match "display_image" =>'home#display_image',:as=>'display_image'
  resources :report_templates
  root :to => "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates_presence_of :name
  validates_uniqueness_of :name,:scope => :project_id
  scope :by_status,lambda{|status| where("status = ?",status)}
  STATUSES =['Due' ,'Completed']
  before_create :set_default_status

  def self.due_task
    Task.by_status(STATUSES[0])
  end

  def self.completed_task
    Task.by_status(STATUSES[1])
  end
  #liquid_methods(:name,:description,:start_date,:end_date,:user_id,:status)
  def completed?
    self.status == STATUSES[1]
  end

  def set_default_status
    self.status = "Due"
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  before_filter :load_project,:except => 'index'
  def index
    @projects = Project.all
    if params[:project_id].blank?
      @tasks = Task.all
      @project_id = ""
    else
      @project = Project.find(params[:project_id])
      @project_id = @project.id
      @tasks =  @project.tasks
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = @project.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = @project.tasks.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = @project.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = @project.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(project_path(@project), :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = @project.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html {redirect_to(project_path(@project), :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(project_tasks_url(@project)) }
      format.xml  { head :ok }
      format.js   { render :nothing => true }
      # or format.js
    end
  end

  def update_task_status
    @task = @project.tasks.find(params[:id])
    @task.status = @task.status == Task::STATUSES[0] ? Task::STATUSES[1] : Task::STATUSES[0]
    @task.save
    respond_to do |format|
      format.js
    end
  end

  private
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project,@task],:html=>{:class=>'data-form'}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%#= f.date_select :start_date %>
    <%= f.text_field :start_date,:id=>"start_date" %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date,:id=>"end_date" %>
  </div>

  <div class="field">
    <%= f.label "user" %><br />
    <%= f.collection_select :user_id,User.all,:id,:name,{},:class=>'flexselect' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    <%= stylesheet_link_tag 'flexselect' %>
<%= content_for :javascripts do%>

    <%= javascript_include_tag 'jquery-ui' %>
    <%= javascript_include_tag 'liquidmetal' %>
    <%= javascript_include_tag 'jquery.flexselect' %>


    <script type="text/javascript">
    $(document).ready(function(){
         $("select.flexselect").flexselect();
        $("#start_date" ).datepicker();
        $("#end_date" ).datepicker();
    });
    </script>
<% end %>

app/views/tasks/destroy.js.erb
$("#<%= dom_id(@task) %>").fadeOut();

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', project_task_path(@project,@task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<% content_for :title do %>
    Tasks
<% end %>

<div style="float:right;padding:5px 20px">
  <% form_tag(task_list_path(),:method=>"get",:id=>'project_list_form') do %>
      <%= select_tag :project_id, options_for_select(@projects.collect{|p| [p.name,p.id]},@project_id),{:include_blank => true}%>
  <% end %>
</div>
<div class="listing">
  <table>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>User</th>
      <th>Status</th>
      <th width="30"></th>
    </tr>

    <% @tasks.each do |task| %>
        <tr id="<%= dom_id(task)%>">
          <td><%=link_to  task.name,project_task_path(task.project,task) %></td>
          <td><%= task.description.truncate(60) %></td>
          <td><%= task.start_date %></td>
          <td><%= task.end_date %></td>
          <td><%= task.user.name rescue "" %></td>
          <td id="task_status_<%=task.id %>"><%= link_to task.status,update_task_status_project_task_path(task.project,task),:remote=>true %></td>
          <td><%= link_to image_tag('edit_10.png'), edit_project_task_path(task.project,task) %>
            <%= link_to image_tag('delete_10.png'), project_task_path(task.project,task), :confirm => 'Are you sure?', :method => :delete,:remote=>true,:class=>'delete-task' %></td>
        </tr>
    <% end %>
  </table>
</div>
<br />
<% if @project %>
    <%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>
<% content_for :javascripts do %>

    <script type="text/javascript">
        $('.delete-task').bind('ajax:success', function() {
            $(this).closest('tr').fadeOut();
        });

        $("#project_id").live("change",function(){
            $("#project_list_form").submit();
        });
    </script>
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/update_task_status.js.erb
$("#task_status_<%=@task.id %>>a").text("<%= escape_javascript(@task.status) %>")