config/routes.rb
DynamicReport::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        get :update_task_status
      end
    end
  end

  resources :reports do
    member do
      get :generate_pdf
    end
  end
  match 'task_list/(:id)' => 'tasks#index' ,:as=>'task_list'
  match "display_image" =>'home#display_image',:as=>'display_image'
  resources :report_templates
  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
   
  has_many :tasks,:dependent => :destroy
  has_many :reports,:dependent => :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
  #liquid_methods :name,:start_date,:description,:end_date

  def to_liquid
    ProjectDrop.new(self) 
  end

#  def to_liquid
#    {
#            'name'=>self.name,
#            'start_date'=>self.start_date,
#            'end_date'=>self.end_date,
#            'description'=>self.description,
#            'draw_pie_chart_for_completed_vs_pending_task'=>self.draw_pie_chart_for_completed_vs_pending_task
#    }
#  end


  def render_graph
    file_name = "#{Dir.tmpdir}/#{self.name}#{Time.now.strftime('%s')}.jpg"
    ch  = self.draw_pie_chart_for_completed_vs_pending_task
   # ch.render_png(file_name)
    ch.export_image(file_name)
    file_name
  end
  

  def draw_pie_chart_for_completed_vs_pending_task
    completed_count = self.tasks.by_status("Completed").count
    pending_count = self.tasks.by_status("Due").count

    r1 = Rdata.new
    r1.add_point([completed_count,pending_count],"Serie1")
    r1.add_point(["Completed","Pending"],"Serie2")
    r1.add_all_series
    r1.set_abscise_label_serie("Serie2")

    ch = Rchart.new(300,200)
    ch.set_font_properties("tahoma.ttf",8)
    ch.draw_filled_rounded_rectangle(7,7,293,193,5,240,240,240)
    ch.draw_rounded_rectangle(5,5,295,195,5,230,230,230)

    # Draw the pie chart
    ch.antialias_quality=0
    ch.set_shadow_properties(2,2,200,200,200)
    ch.draw_flat_pie_graph_with_shadow(r1.get_data,r1.get_data_description,120,100,60,Rchart::PIE_PERCENTAGE,8)
    ch.clear_shadow
    ch.draw_pie_legend(200,15,r1.get_data,r1.get_data_description,250,250,250)
    ch.draw_title(10,20,"Completed vs Pending",100,100,100)

    return ch
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
require "tempfile"
module ProjectsHelper
  def draw_task_status_graph_for_pdf(project=Project.first)

   graph = project.draw_pie_chart_for_completed_vs_pending_task
   filename = "#{project.name}#{Time.now.strftime('%s')}.png"
   file = Tempfile.new(filename)
   file = file.binmode
   file.write(graph.render_png_str)
   file.close
   #content_tag(:div, file.path), :class => "graphs")
    #"<img src=#{file.path}></img>"
    content_tag(:img,'',:src=> file.path)
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project,:html=>{:class=>'data-form'}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%#= f.date_select :start_date %>
    <%= f.text_field :start_date,:id=>'start_date' %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :start_date,:id=>'end_date' %>
    <%#= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= content_for :javascripts do%>
    <%= javascript_include_tag 'jquery-ui' %>
    <script type="text/javascript">
    $(document).ready(function(){
        $("#start_date" ).datepicker();
        $("#end_date" ).datepicker();
    });
    </script>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% content_for :title do%>
 Projects
<% end %>
<div class="listing">
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th width="30"></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%=link_to project.name,project_path(project) %></td>
    <td><%= project.description.truncate(60) %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= link_to image_tag('edit_10.png'), edit_project_path(project) %>
    <%= link_to image_tag('delete_10.png'), project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p class="default-show">
  <strong>Name: </strong>
  <%= @project.name %>
  <div style="padding:10px;">
    <strong>Start date:</strong>
    <%= @project.start_date %>
    <span style="float:right">
        <strong>End date:</strong>
      <%= @project.end_date %>
    </span>
   </div>

</p>

<p class="default-show">
  <strong>Description:</strong>
    <p class="default-show">
      <%= @project.description %>
    </p>
</p>
<div class="listing">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Owner</th>
        <th width="30"></th>
       </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>

        <tr>
          <td><%= link_to  task.name,project_task_path(@project,task) %></td>
          <td><%= task.description %></td>
          <td><%= task.start_date %></td>
          <td><%= task.owner.name rescue ""%></td>
          <td><%= link_to image_tag('edit_10.png'), edit_project_task_path(@project,task) %>
       <%= link_to image_tag('delete_10.png'), project_task_path(@project,task), :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="5"><%= link_to "Add task",new_project_task_path(@project) %></td>
      </tr>
    </tfoot>
  </table>
</div>




<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>