config/routes.rb
DynamicReport::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        get :update_task_status
      end
    end
  end

  resources :reports do
    member do
      get :generate_pdf
    end
  end
  match 'task_list/(:id)' => 'tasks#index' ,:as=>'task_list'
  match "display_image" =>'home#display_image',:as=>'display_image'
  resources :report_templates
  root :to => "home#index"

end

app/models/report.rb
require 'liquid_filter'
class Report < ActiveRecord::Base
  belongs_to :report_template
  belongs_to :project
  before_save :update_content
  def update_content
    self.template_content = self.report_template.template_content #if self.template_content.blank?
    self.report_name = self.report_template.template_name
    arguments = {
            "project"=>self.project,
            "tasks"=>self.project.tasks,
            "pending_tasks"=>self.project.tasks.due_task,
            "completed_tasks"=>self.project.tasks.completed_task,
            "draw_task_status_graph"=>self.project.render_graph
    }

    content= self.template_content
    content = Liquid::Template.parse(content).render(arguments,:filters => [LiquidFilter])
    content = TidyFFI::Tidy.new(content, :show_body_only => 1,:output_xhtml=>1).clean
    content=content.gsub(/\n/,'')
    self.report_content = content
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  acts_as_flying_saucer
  # GET /reports
  # GET /reports.xml
  include ProjectsHelper
  def index
    @projects = Project.all
    @report_templates = ReportTemplate.all
    @reports = Report.all
    @report = Report.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end



  # POST /reports
  # POST /reports.xml
  def create


    @report = Report.new(params[:report])
    respond_to do |format|
      if @report.save
        format.html { redirect_to(@report, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end
  def generate_pdf
    @report = Report.find(params[:id])
    arguments =   {"project"=>@report.project}
    @report_content =Liquid::Template.parse(@report.report_content).render(arguments,:filters => [LiquidFilter])
    respond_to do |format|
      format.pdf {
        render_pdf :template => 'reports/generate_pdf.pdf.erb',
                   :send_file => { :filename => "#{@report.report_name.to_s}.pdf"},
                   :debug_html =>params[:html_view]
      }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

end

app/views/reports/generate_pdf.pdf.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <%= stylesheet_link_tag "pdf",:media => 'print'%>

  <style>
      /* PAGE, HEADERS, FOOTERS */
      /*.header { position: running(header) }*/
      @page {
          size: A4;
          border-top: 1px solid black;
          border-bottom: 1px solid black;
          margin: 8% 5% 6% 6%;
          counter-increment: page;
      @top-left {
      font-family : Arial, Helvetica, sans-serif;
          font-size: 11px;
          text-align: left;
          content: "Resume" ;
          vertical-align: bottom;
          padding: 3px;
      }
      @top-right {
        font-family : Arial, Helvetica, sans-serif;
        font-size: 11px;
        text-align: right;
        content: "<%= @report.project.name%>" ;
        vertical-align: bottom;
        padding: 3px;
      }
      @bottom-left {
        font-family : Arial, Helvetica, sans-serif;
        font-size: 9px;
        content: "Report generated on <%=Time.now.to_s(:long) %>";
        vertical-align: top;
        padding: 3px;
      }
      @bottom-right {
        font-family : Arial, Helvetica, sans-serif;
        font-size: 12px;
        content: "Page " counter(page) " of " counter(pages);
        vertical-align: top;
        padding: 3px;
        text-align: right;
      }
      }

      /* BODY CSS */
      body {
          font-size: 13px;
          font-family: Arial, Helvetica, sans-serif;
          background-color:white;
      }

      h2 { padding-top: 10px; }


      p.small-text { font-size: 11px; }

      div.graph { text-align: center;  }


      .page_break{page-break-after:always}
      p{font-size:13px}


  </style>
</head>
<body>
<%= @report_content.html_safe %>
</body>
</html>

app/views/reports/index.html.erb
<% content_for :title do %>
 Reports
<% end %>
<div>
<% form_for(@report) do |f| %>
<strong>Project:</strong><%=f.collection_select :project_id,@projects,:id,:name %>
<strong>Report Template</strong><%=f.collection_select :report_template_id,@report_templates,:id,:template_name %>
 <%= f.submit "Submit" %>     
<% end %>
</div>
<div class="listing">
<table>
  <tr>
    <th>Report name</th>
    <th width="30"></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%=link_to report.report_name,report_path(report) %></td>
    <td><%= link_to image_tag('delete_10.png'), report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />

app/views/reports/show.html.erb
<div>
  <%= link_to "Pdf",generate_pdf_report_path(@report,:format=>:pdf) %>|
  <%= link_to "Html",generate_pdf_report_path(@report,:format=>:pdf,:html_view=>true) %>
</div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Report name:</strong>
  <%= @report.report_name %>
</p>

<p>
  <strong>Report content:</strong>
  <br />
  <%=raw @report.report_content %>

</p>
<%= draw_task_status_graph_for_pdf(Project.first)%>

<%#= image_tag "/tmp/Test.png" %>
 <%#= image_tag(display_image_path(:file_name=>"/tmp/Test.png")) %>
<%= link_to 'Back', reports_path %>