config/routes.rb
DynamicReport::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        get :update_task_status
      end
    end
  end

  resources :reports do
    member do
      get :generate_pdf
    end
  end
  match 'task_list/(:id)' => 'tasks#index' ,:as=>'task_list'
  match "display_image" =>'home#display_image',:as=>'display_image'
  resources :report_templates
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'jquery-ui','reset','grid','application'%>
  <%= javascript_include_tag :defaults %>
  <title>Dynamic Report In Ruby  <%=raw ((yield(:title) || "Untitled")) %></title>
  <%= yield :head %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container_16 every-thing">

  <div class="header">
    <div class="grid_16">
      <div class="grid_8" >
        <div class="login-bar-left"><h1>Dymanic Report In Ruby On Rails</h1></div>
      </div>
      <div class="grid_8">
        <div id="login-bar-right">
          <ul>
            <% if !current_user.blank? %>
                <li><%= link_to "Logout",  destroy_user_session_path%></li>
                <li><%=link_to "Profile | ", edit_user_registration_path %> </li>

            <% else %>
                <li><%= link_to "Register ", new_user_registration_path %></li>
                <li><%= link_to "Login | ", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <%= clearing_span %>
    <div class="main-nav">
      <ul>
        <% if current_user.blank? %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Register ", new_user_registration_path %></li>
        <% else %>
            <li><%= link_to "Home", root_url, :method => :delete %></li>
            <li><%= link_to "Project",projects_path %></li>
            <li><%= link_to "Tasks",task_list_path() %></li>
            <li><%= link_to "Template",report_templates_path() %></li>
             <li><%= link_to "Report",reports_path() %></li>
        <% end %>

      </ul>
    </div>
  </div>
  <%= clearing_span %>
  <div id="wrapper">
    <div id="content" class="<%= main_content_css_class %>">
      <%= title  yield :title %>
      <%= yield %>
    </div>
    <div class="<%=  sidebar_css_class %>">
      <%=yield :sidebar %>
    </div>
    <%= clearing_span %>
  </div>

  <div class="push"></div>

</div>



<div class="container_16">

  <div id="footer">
    <p class="copyright">&copy; 2010 <a href="http://raistech.com">Amar Daxini</a></p>
  </div>
  <%= yield :javascripts %>

</div>
</body>
</html>